### ISSUE TITLE
Remove brotli-size dependency from bundlesize fork

### ISSUE THREAD

**Issue by kefranabg** [kefranabg/bento-starter#151]
In `bento-starter` we do not check js bundle size with brotli compression. so we can remove this dependency from [my bundle size fork](https://github.com/kefranabg/bundlesize).

**Why removing `brotli-size` dependency ?**

Having `brotli-size` in bento-starter dependencies is a mess. `brotli-size` depends on `iltorb` and `iltorb` force users to install python 2.7 and g++ compiler. In addition, it's not compatible with Node.js 12.

**Tasks** :

- [x] Edit [this file](https://github.com/kefranabg/bundlesize/blob/master/src/compressed-size.js) and remove 'brotli' case.
- [x] Check bento-starter does not need `brotli-size`dependency anymore
- [x] Try install bento-starter without python 2.7 & g++ compiler; Check Node.js 12 compatibility
- [x] Edit bento-starter-docs to remove prerequisites (python 2.7 && nodejs < 12)

**Comment by kefranabg** [comment]
Another option would be to add brotli-size as an optionnal dependency. Check this [PR](https://github.com/siddharthkp/bundlesize/pull/299/commits/4a4a2808ed3480000b96a82c1d7e1575ac159b82)
